<a href="https://colab.research.google.com/github/snehasingh979/Data-science-with-AI/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Pandas

pandas is an open-source python library used for data for data manipulation and data analysis

Why do we use pandas?

pandas is used read,clean,organzie,filter,analze,and manipulate strutureed data efficiently

feature of pandas

1.Data manipulation

used to modify organzie and transform data easily

2.Data analysis

used to analyze data extract meaningful insights

3.Fast processing

handle large dataset efficiently with optimized performace

4.Missing value handling

allow easy detection and handling of misssing value

5.File handling

can read and write CSV ,excel,json,sql,and many other file formate

6.Data filtering

used to select specific row and colums based on condition

7.Data cleaning

remove dulicate incorrect or uncessary data

8.Statistical analysis
provide

Main Data Structure in Pandas

1.series A series is one-dimensional labeled aaray that store a single colume of data


2.Data frame A dataframe is two-dimiensional labeled array consisting row and columns

1.Creating series

In [ ]:
import pandas as np
marks = np.Series([85,90,78,92,88])
print(marks)

0    85
1    90
2    78
3    92
4    88
dtype: int64

creating a series of string

In [ ]:
import pandas as np
fruits = np.Series(['apple','banana','orange','mango'])
print(fruits)

0     apple
1    banana
2    orange
3     mango
dtype: object

creating a series with custom index

In [ ]:
import pandas as np
marks = np.Series([85,90,78,92,88],index=['ram','shyam','hari','gita','sita'])
print(marks)

creating a series form a dictionary

In [ ]:
import pandas as pd
student = pd.Series({"Name":"Aman","Age":20,"city":"delhi"})
print(student)

Name     Aman
Age        20
city    delhi
dtype: object

Access value in  a series

In [ ]:
import pandas as pd
marks = pd.Series([85,90,78,92,88],index=['ram','shyam','hari','gita','sita'])
print(marks[2])

78

/tmp/ipykernel_4626/698897383.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(marks[2])

Access value using  custom index

In [ ]:
import pandas as pd
marks = pd.Series([85,90,78,92,88],index=['ram','shyam','hari','gita','sita'])
print(marks['hari'])

78

Print Series information

In [ ]:
import pandas as pd
marks = pd.Series([85,90,78,92,88],index=['ram','shyam','hari','gita','sita'])
print(marks.dtype)

int64

2.creating Data frame

dataframe is a two dimensional labeled table consisting of row and columne A  data frame is used to store, organzinng ,manipulate,and analyzer tabular data efficienctly

syntax

important pandas as pd df=pd.data frame(data)

In [ ]:
import pandas as pd
student={
    "Name":["Aman","Ravi","priya","neha"],
    "Age":[20,21,19,22],
    "city":["delhi","lucknow","ghaziabad","noida"]
}
df=pd.DataFrame(student)
print(df)

    Name  Age       city
0   Aman   20      delhi
1   Ravi   21    lucknow
2  priya   19  ghaziabad
3   neha   22      noida

create dataframe with customer index

In [ ]:
import pandas as pd
student={
    "Name":["Aman","Ravi","priya","neha"],
    "Marks":[85,90,78,92],
    "city":["delhi","lucknow","ghaziabad","noida"]
}
df=pd.DataFrame(student,index=["s1","s2","s3","s4"])
print(df)

     Name  Marks       city
s1   Aman     85      delhi
s2   Ravi     90    lucknow
s3  priya     78  ghaziabad
s4   neha     92      noida

create dataframe from a list of list

In [ ]:
import pandas as pd
data=[
    ["Aman",85,"delhi"],
    ["Ravi",90,"lucknow"],
    ["priya",78,"ghaziabad"],
    ["neha",92,"noida"]
]
df=pd.DataFrame(data,columns=["Name","Marks","city"])
print(df)

    Name  Marks       city
0   Aman     85      delhi
1   Ravi     90    lucknow
2  priya     78  ghaziabad
3   neha     92      noida

create dataframe from a list of Dictionaries

In [ ]:
import pandas as pd
data=[
    {"Name":"Aman","Age":20},
    {"Name":"Ravi","Age":21},
    {"Name":"priya","Age":19},
    {"Name":"neha","Age":22}
]
df=pd.DataFrame(data)
print(df)

    Name  Age
0   Aman   20
1   Ravi   21
2  priya   19
3   neha   22

creaate an empty dataframe

In [ ]:
import pandas as pd
df_empty = pd.DataFrame()
print(df_empty)

Empty DataFrame
Columns: []
Index: []

2.Module -Reading and writing data

1-read_csv()

In [ ]:
import pandas as pd
df=pd.read_csv("/content/student.csv")
print(df)

    school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
0       GP   F   18       U     GT3       A     4     4   at_home   teacher
1       GP   F   17       U     GT3       T     1     1   at_home     other
2       GP   F   15       U     LE3       T     1     1   at_home     other
3       GP   F   15       U     GT3       T     4     2    health  services
4       GP   F   16       U     GT3       T     3     3     other     other
..     ...  ..  ...     ...     ...     ...   ...   ...       ...       ...
390     MS   M   20       U     LE3       A     2     2  services  services
391     MS   M   17       U     LE3       T     3     1  services  services
392     MS   M   21       R     GT3       T     1     1     other     other
393     MS   M   18       R     LE3       T     3     2  services     other
394     MS   M   19       U     LE3       T     1     1     other   at_home

     ... famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3
0    ...      4        3      4     1     1      3        6   5   6   6
1    ...      5        3      3     1     1      3        4   5   5   6
2    ...      4        3      2     2     3      3       10   7   8  10
3    ...      3        2      2     1     1      5        2  15  14  15
4    ...      4        3      2     1     2      5        4   6  10  10
..   ...    ...      ...    ...   ...   ...    ...      ...  ..  ..  ..
390  ...      5        5      4     4     5      4       11   9   9   9
391  ...      2        4      5     3     4      2        3  14  16  16
392  ...      5        5      3     3     3      3        3  10   8   7
393  ...      4        4      1     3     4      5        0  11  12  10
394  ...      3        2      3     3     3      5        5   8   9   9

[395 rows x 33 columns]

Display first five rows

In [ ]:
import pandas as pd
df=pd.read_csv("/content/student.csv")
print(df.head())

  school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  ...  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher  ...
1     GP   F   17       U     GT3       T     1     1  at_home     other  ...
2     GP   F   15       U     LE3       T     1     1  at_home     other  ...
3     GP   F   15       U     GT3       T     4     2   health  services  ...
4     GP   F   16       U     GT3       T     3     3    other     other  ...

  famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3
0      4        3      4     1     1      3        6   5   6   6
1      5        3      3     1     1      3        4   5   5   6
2      4        3      2     2     3      3       10   7   8  10
3      3        2      2     1     1      5        2  15  14  15
4      4        3      2     1     2      5        4   6  10  10

[5 rows x 33 columns]

In [ ]:
import pandas as pd
df=pd.read_csv("/content/student.csv")
print(df.head(10))

  school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
0     GP   F   18       U     GT3       A     4     4   at_home   teacher
1     GP   F   17       U     GT3       T     1     1   at_home     other
2     GP   F   15       U     LE3       T     1     1   at_home     other
3     GP   F   15       U     GT3       T     4     2    health  services
4     GP   F   16       U     GT3       T     3     3     other     other
5     GP   M   16       U     LE3       T     4     3  services     other
6     GP   M   16       U     LE3       T     2     2     other     other
7     GP   F   17       U     GT3       A     4     4     other   teacher
8     GP   M   15       U     LE3       A     3     2  services     other
9     GP   M   15       U     GT3       T     3     4     other     other

   ... famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3
0  ...      4        3      4     1     1      3        6   5   6   6
1  ...      5        3      3     1     1      3        4   5   5   6
2  ...      4        3      2     2     3      3       10   7   8  10
3  ...      3        2      2     1     1      5        2  15  14  15
4  ...      4        3      2     1     2      5        4   6  10  10
5  ...      5        4      2     1     2      5       10  15  15  15
6  ...      4        4      4     1     1      3        0  12  12  11
7  ...      4        1      4     1     1      1        6   6   5   6
8  ...      4        2      2     1     1      1        0  16  18  19
9  ...      5        5      1     1     1      5        0  14  15  15

[10 rows x 33 columns]

Display last 5 rows

In [ ]:
import pandas as pd
df=pd.read_csv("/content/student.csv")
print(df.tail())

    school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
390     MS   M   20       U     LE3       A     2     2  services  services
391     MS   M   17       U     LE3       T     3     1  services  services
392     MS   M   21       R     GT3       T     1     1     other     other
393     MS   M   18       R     LE3       T     3     2  services     other
394     MS   M   19       U     LE3       T     1     1     other   at_home

     ... famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3
390  ...      5        5      4     4     5      4       11   9   9   9
391  ...      2        4      5     3     4      2        3  14  16  16
392  ...      5        5      3     3     3      3        3  10   8   7
393  ...      4        4      1     3     4      5        0  11  12  10
394  ...      3        2      3     3     3      5        5   8   9   9

[5 rows x 33 columns]

Store using Another variable name

In [ ]:
import pandas as pd
students = pd.read_csv("/content/student.csv")
print(students.head())

  school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  ...  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher  ...
1     GP   F   17       U     GT3       T     1     1  at_home     other  ...
2     GP   F   15       U     LE3       T     1     1  at_home     other  ...
3     GP   F   15       U     GT3       T     4     2   health  services  ...
4     GP   F   16       U     GT3       T     3     3    other     other  ...

  famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3
0      4        3      4     1     1      3        6   5   6   6
1      5        3      3     1     1      3        4   5   5   6
2      4        3      2     2     3      3       10   7   8  10
3      3        2      2     1     1      5        2  15  14  15
4      4        3      2     1     2      5        4   6  10  10

[5 rows x 33 columns]

Read selected columns

In [ ]:
import pandas as pd
df = pd.read_csv("/content/student.csv",usecols=["sex","G1","G2"])
print(df)

    sex  G1  G2
0     F   5   6
1     F   5   5
2     F   7   8
3     F  15  14
4     F   6  10
..   ..  ..  ..
390   M   9   9
391   M  14  16
392   M  10   8
393   M  11  12
394   M   8   9

[395 rows x 3 columns]

2.read_excel()

read_excel() is used to read data frame an excel (.xlsx) file and load it in into a pandas dataframe

Prerequisite

to read excel files,install the openpyxl library

In [ ]:
import pandas as pd
df=pd.read_csv("/content/student.csv")
df.to_excel("student.xlsx",index=False)
print("csv sucessfully converted to excel")

csv sucessfully converted to excel

Read Excel file

In [ ]:
import pandas as pd
df=pd.read_excel("/content/student.xlsx")
print(df)

    school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
0       GP   F   18       U     GT3       A     4     4   at_home   teacher
1       GP   F   17       U     GT3       T     1     1   at_home     other
2       GP   F   15       U     LE3       T     1     1   at_home     other
3       GP   F   15       U     GT3       T     4     2    health  services
4       GP   F   16       U     GT3       T     3     3     other     other
..     ...  ..  ...     ...     ...     ...   ...   ...       ...       ...
390     MS   M   20       U     LE3       A     2     2  services  services
391     MS   M   17       U     LE3       T     3     1  services  services
392     MS   M   21       R     GT3       T     1     1     other     other
393     MS   M   18       R     LE3       T     3     2  services     other
394     MS   M   19       U     LE3       T     1     1     other   at_home

     ... famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3
0    ...      4        3      4     1     1      3        6   5   6   6
1    ...      5        3      3     1     1      3        4   5   5   6
2    ...      4        3      2     2     3      3       10   7   8  10
3    ...      3        2      2     1     1      5        2  15  14  15
4    ...      4        3      2     1     2      5        4   6  10  10
..   ...    ...      ...    ...   ...   ...    ...      ...  ..  ..  ..
390  ...      5        5      4     4     5      4       11   9   9   9
391  ...      2        4      5     3     4      2        3  14  16  16
392  ...      5        5      3     3     3      3        3  10   8   7
393  ...      4        4      1     3     4      5        0  11  12  10
394  ...      3        2      3     3     3      5        5   8   9   9

[395 rows x 33 columns]

Diplay first five rows

In [ ]:
import pandas as pd
df=pd.read_excel("/content/student.xlsx")
print(df.head())

  school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  ...  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher  ...
1     GP   F   17       U     GT3       T     1     1  at_home     other  ...
2     GP   F   15       U     LE3       T     1     1  at_home     other  ...
3     GP   F   15       U     GT3       T     4     2   health  services  ...
4     GP   F   16       U     GT3       T     3     3    other     other  ...

  famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3
0      4        3      4     1     1      3        6   5   6   6
1      5        3      3     1     1      3        4   5   5   6
2      4        3      2     2     3      3       10   7   8  10
3      3        2      2     1     1      5        2  15  14  15
4      4        3      2     1     2      5        4   6  10  10

[5 rows x 33 columns]

Displays last five rows

In [ ]:
import pandas as pd
df=pd.read_excel("/content/student.xlsx")
print(df.tail())

    school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
390     MS   M   20       U     LE3       A     2     2  services  services
391     MS   M   17       U     LE3       T     3     1  services  services
392     MS   M   21       R     GT3       T     1     1     other     other
393     MS   M   18       R     LE3       T     3     2  services     other
394     MS   M   19       U     LE3       T     1     1     other   at_home

     ... famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3
390  ...      5        5      4     4     5      4       11   9   9   9
391  ...      2        4      5     3     4      2        3  14  16  16
392  ...      5        5      3     3     3      3        3  10   8   7
393  ...      4        4      1     3     4      5        0  11  12  10
394  ...      3        2      3     3     3      5        5   8   9   9

[5 rows x 33 columns]

Read first 10 rows

In [ ]:
import pandas as pd
df=pd.read_excel("/content/student.xlsx")
usecols=["sex","G1","G2"]
print(df.head(10))

  school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
0     GP   F   18       U     GT3       A     4     4   at_home   teacher
1     GP   F   17       U     GT3       T     1     1   at_home     other
2     GP   F   15       U     LE3       T     1     1   at_home     other
3     GP   F   15       U     GT3       T     4     2    health  services
4     GP   F   16       U     GT3       T     3     3     other     other
5     GP   M   16       U     LE3       T     4     3  services     other
6     GP   M   16       U     LE3       T     2     2     other     other
7     GP   F   17       U     GT3       A     4     4     other   teacher
8     GP   M   15       U     LE3       A     3     2  services     other
9     GP   M   15       U     GT3       T     3     4     other     other

   ... famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3
0  ...      4        3      4     1     1      3        6   5   6   6
1  ...      5        3      3     1     1      3        4   5   5   6
2  ...      4        3      2     2     3      3       10   7   8  10
3  ...      3        2      2     1     1      5        2  15  14  15
4  ...      4        3      2     1     2      5        4   6  10  10
5  ...      5        4      2     1     2      5       10  15  15  15
6  ...      4        4      4     1     1      3        0  12  12  11
7  ...      4        1      4     1     1      1        6   6   5   6
8  ...      4        2      2     1     1      1        0  16  18  19
9  ...      5        5      1     1     1      5        0  14  15  15

[10 rows x 33 columns]

Read selected columns

In [ ]:
import pandas as pd
df=pd.read_excel("/content/student.xlsx")
usecols=["sex","G1","G2"]
print(df)

    school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
0       GP   F   18       U     GT3       A     4     4   at_home   teacher
1       GP   F   17       U     GT3       T     1     1   at_home     other
2       GP   F   15       U     LE3       T     1     1   at_home     other
3       GP   F   15       U     GT3       T     4     2    health  services
4       GP   F   16       U     GT3       T     3     3     other     other
..     ...  ..  ...     ...     ...     ...   ...   ...       ...       ...
390     MS   M   20       U     LE3       A     2     2  services  services
391     MS   M   17       U     LE3       T     3     1  services  services
392     MS   M   21       R     GT3       T     1     1     other     other
393     MS   M   18       R     LE3       T     3     2  services     other
394     MS   M   19       U     LE3       T     1     1     other   at_home

     ... famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3
0    ...      4        3      4     1     1      3        6   5   6   6
1    ...      5        3      3     1     1      3        4   5   5   6
2    ...      4        3      2     2     3      3       10   7   8  10
3    ...      3        2      2     1     1      5        2  15  14  15
4    ...      4        3      2     1     2      5        4   6  10  10
..   ...    ...      ...    ...   ...   ...    ...      ...  ..  ..  ..
390  ...      5        5      4     4     5      4       11   9   9   9
391  ...      2        4      5     3     4      2        3  14  16  16
392  ...      5        5      3     3     3      3        3  10   8   7
393  ...      4        4      1     3     4      5        0  11  12  10
394  ...      3        2      3     3     3      5        5   8   9   9

[395 rows x 33 columns]

Read.json()

In [ ]:
import pandas as pd
df=pd.read_csv("/content/student.csv")
df.to_json("student.json")
print("csv sucessfully converted to json")

csv sucessfully converted to json

read files

In [ ]:
import pandas as pd
df=pd.read_json("/content/student.json")
print(df)

    school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
0       GP   F   18       U     GT3       A     4     4   at_home   teacher
1       GP   F   17       U     GT3       T     1     1   at_home     other
2       GP   F   15       U     LE3       T     1     1   at_home     other
3       GP   F   15       U     GT3       T     4     2    health  services
4       GP   F   16       U     GT3       T     3     3     other     other
..     ...  ..  ...     ...     ...     ...   ...   ...       ...       ...
390     MS   M   20       U     LE3       A     2     2  services  services
391     MS   M   17       U     LE3       T     3     1  services  services
392     MS   M   21       R     GT3       T     1     1     other     other
393     MS   M   18       R     LE3       T     3     2  services     other
394     MS   M   19       U     LE3       T     1     1     other   at_home

     ... famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3
0    ...      4        3      4     1     1      3        6   5   6   6
1    ...      5        3      3     1     1      3        4   5   5   6
2    ...      4        3      2     2     3      3       10   7   8  10
3    ...      3        2      2     1     1      5        2  15  14  15
4    ...      4        3      2     1     2      5        4   6  10  10
..   ...    ...      ...    ...   ...   ...    ...      ...  ..  ..  ..
390  ...      5        5      4     4     5      4       11   9   9   9
391  ...      2        4      5     3     4      2        3  14  16  16
392  ...      5        5      3     3     3      3        3  10   8   7
393  ...      4        4      1     3     4      5        0  11  12  10
394  ...      3        2      3     3     3      5        5   8   9   9

[395 rows x 33 columns]

In [ ]:
#frist five rows
import pandas as pd
df=pd.read_json("/content/student.json")
print(df.head())

  school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  ...  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher  ...
1     GP   F   17       U     GT3       T     1     1  at_home     other  ...
2     GP   F   15       U     LE3       T     1     1  at_home     other  ...
3     GP   F   15       U     GT3       T     4     2   health  services  ...
4     GP   F   16       U     GT3       T     3     3    other     other  ...

  famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3
0      4        3      4     1     1      3        6   5   6   6
1      5        3      3     1     1      3        4   5   5   6
2      4        3      2     2     3      3       10   7   8  10
3      3        2      2     1     1      5        2  15  14  15
4      4        3      2     1     2      5        4   6  10  10

[5 rows x 33 columns]

In [ ]:
#last 5 row
import pandas as pd
df=pd.read_json("/content/student.json")
print(df.tail())

    school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
390     MS   M   20       U     LE3       A     2     2  services  services
391     MS   M   17       U     LE3       T     3     1  services  services
392     MS   M   21       R     GT3       T     1     1     other     other
393     MS   M   18       R     LE3       T     3     2  services     other
394     MS   M   19       U     LE3       T     1     1     other   at_home

     ... famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3
390  ...      5        5      4     4     5      4       11   9   9   9
391  ...      2        4      5     3     4      2        3  14  16  16
392  ...      5        5      3     3     3      3        3  10   8   7
393  ...      4        4      1     3     4      5        0  11  12  10
394  ...      3        2      3     3     3      5        5   8   9   9

[5 rows x 33 columns]

Sample ()


the sample () function is used to selected random row and from dataframe

it is widely used in

1. machine learning
2.data analysis
3.data visualization
4.random testing
5.survey analysis
6.exploratory data analysis

Display one random student

In [ ]:
import pandas as pd
df=pd.read_json("/content/student.json")
print(df.sample())

   school sex  age address famsize Pstatus  Medu  Fedu     Mjob     Fjob  ...  \
32     GP   M   15       R     GT3       T     4     3  teacher  at_home  ...

   famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3
32      4        5      2     1     1      5        0  17  16  16

[1 rows x 33 columns]

In [ ]:
import pandas as pd
df=pd.read_json("/content/student.json")
print(df.sample(5))

    school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
379     MS   F   17       R     GT3       T     3     1   at_home     other
37      GP   M   16       R     GT3       A     4     4     other   teacher
8       GP   M   15       U     LE3       A     3     2  services     other
290     GP   M   18       U     GT3       T     4     2   teacher     other
390     MS   M   20       U     LE3       A     2     2  services  services

     ... famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3
379  ...      4        5      4     2     3      1       17  10  10  10
37   ...      2        4      3     1     1      5        7  15  16  15
8    ...      4        2      2     1     1      1        0  16  18  19
290  ...      4        3      2     1     4      5       11  12  11  11
390  ...      5        5      4     4     5      4       11   9   9   9

[5 rows x 33 columns]

select 30% of Dataset

In [ ]:
import pandas as pd
df=pd.read_json("/content/student.json")
print(df.sample(frac=0.3))

    school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
231     GP   M   17       R     GT3       T     2     2     other     other
265     GP   M   18       R     LE3       A     3     4     other     other
341     GP   M   18       U     GT3       T     4     4   teacher  services
147     GP   F   15       U     GT3       T     1     2   at_home     other
359     MS   F   18       U     LE3       T     1     1   at_home  services
..     ...  ..  ...     ...     ...     ...   ...   ...       ...       ...
271     GP   F   18       U     GT3       T     2     3     other  services
33      GP   M   15       U     LE3       T     3     3     other     other
284     GP   F   17       U     GT3       T     2     2     other     other
288     GP   M   18       U     GT3       T     2     1  services  services
326     GP   M   17       U     GT3       T     3     3     other  services

     ... famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3
231  ...      4        5      2     1     1      1        4  11  11  11
265  ...      4        2      5     3     4      1       13  17  17  17
341  ...      4        3      3     2     2      2        0  10  10   0
147  ...      4        3      2     1     1      5        2  10  11  11
359  ...      5        3      2     1     1      4        0  18  16  16
..   ...    ...      ...    ...   ...   ...    ...      ...  ..  ..  ..
271  ...      4        5      5     1     3      2        4  15  14  14
33   ...      5        3      2     1     1      2        0   8  10  12
284  ...      5        4      5     1     2      5        4  10   9  11
288  ...      4        2      4     1     3      2        6  15  14  14
326  ...      4        3      5     3     5      5        3  14  15  16

[118 rows x 33 columns]

Random student  from excel file

In [ ]:
import pandas as pd
df=pd.read_excel("/content/student.xlsx")
print(df.sample(3))

    school sex  age address famsize Pstatus  Medu  Fedu      Mjob   Fjob  ...  \
207     GP   F   16       U     GT3       T     4     3   teacher  other  ...
5       GP   M   16       U     LE3       T     4     3  services  other  ...
379     MS   F   17       R     GT3       T     3     1   at_home  other  ...

    famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3
207      1        3      2     1     1      1       10  11  12  13
5        5        4      2     1     2      5       10  15  15  15
379      4        5      4     2     3      1       17  10  10  10

[3 rows x 33 columns]

Module 3-DataFrame information

In [ ]:
import pandas as pd
df=pd.read_csv("/content/student.csv") # Corrected to read_excel
df.info()
print(df.shape)
print(df.size)
print(df.ndim)
print(df.columns)
print(df.index)
print(df.memory_usage())
print(df.describe())
print(df.describe(include='all'))
print(df.count())
print(df.isnull().sum())
print(df.nunique())
print(df.value_counts()) # Corrected: value_counts() is typically for a Series (column)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      395 non-null    object
 1   sex         395 non-null    object
 2   age         395 non-null    int64
 3   address     395 non-null    object
 4   famsize     395 non-null    object
 5   Pstatus     395 non-null    object
 6   Medu        395 non-null    int64
 7   Fedu        395 non-null    int64
 8   Mjob        395 non-null    object
 9   Fjob        395 non-null    object
 10  reason      395 non-null    object
 11  guardian    395 non-null    object
 12  traveltime  395 non-null    int64
 13  studytime   395 non-null    int64
 14  failures    395 non-null    int64
 15  schoolsup   395 non-null    object
 16  famsup      395 non-null    object
 17  paid        395 non-null    object
 18  activities  395 non-null    object
 19  nursery     395 non-null    object
 20  higher      395 non-null    object
 21  internet    395 non-null    object
 22  romantic    395 non-null    object
 23  famrel      395 non-null    int64
 24  freetime    395 non-null    int64
 25  goout       395 non-null    int64
 26  Dalc        395 non-null    int64
 27  Walc        395 non-null    int64
 28  health      395 non-null    int64
 29  absences    395 non-null    int64
 30  G1          395 non-null    int64
 31  G2          395 non-null    int64
 32  G3          395 non-null    int64
dtypes: int64(16), object(17)
memory usage: 102.0+ KB
(395, 33)
13035
2
Index(['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
       'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc',
       'Walc', 'health', 'absences', 'G1', 'G2', 'G3'],
      dtype='object')
RangeIndex(start=0, stop=395, step=1)
Index          132
school        3160
sex           3160
age           3160
address       3160
famsize       3160
Pstatus       3160
Medu          3160
Fedu          3160
Mjob          3160
Fjob          3160
reason        3160
guardian      3160
traveltime    3160
studytime     3160
failures      3160
schoolsup     3160
famsup        3160
paid          3160
activities    3160
nursery       3160
higher        3160
internet      3160
romantic      3160
famrel        3160
freetime      3160
goout         3160
Dalc          3160
Walc          3160
health        3160
absences      3160
G1            3160
G2            3160
G3            3160
dtype: int64
              age        Medu        Fedu  traveltime   studytime    failures  \
count  395.000000  395.000000  395.000000  395.000000  395.000000  395.000000
mean    16.696203    2.749367    2.521519    1.448101    2.035443    0.334177
std      1.276043    1.094735    1.088201    0.697505    0.839240    0.743651
min     15.000000    0.000000    0.000000    1.000000    1.000000    0.000000
25%     16.000000    2.000000    2.000000    1.000000    1.000000    0.000000
50%     17.000000    3.000000    2.000000    1.000000    2.000000    0.000000
75%     18.000000    4.000000    3.000000    2.000000    2.000000    0.000000
max     22.000000    4.000000    4.000000    4.000000    4.000000    3.000000

           famrel    freetime       goout        Dalc        Walc      health  \
count  395.000000  395.000000  395.000000  395.000000  395.000000  395.000000
mean     3.944304    3.235443    3.108861    1.481013    2.291139    3.554430
std      0.896659    0.998862    1.113278    0.890741    1.287897    1.390303
min      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000
25%      4.000000    3.000000    2.000000    1.000000    1.000000    3.000000
50%      4.000000    3.000000    3.000000    1.000000    2.000000    4.000000
75%      5.000000    4.000000    4.000000    2.000000    3.000000    5.000000
max      5.000000    5.000000    5.000000    5.000000    5.000000    5.000000

         absences          G1          G2          G3
count  395.000000  395.000000  395.000000  395.000000
mean     5.708861   10.908861   10.713924   10.415190
std      8.003096    3.319195    3.761505    4.581443
min      0.000000    3.000000    0.000000    0.000000
25%      0.000000    8.000000    9.000000    8.000000
50%      4.000000   11.000000   11.000000   11.000000
75%      8.000000   13.000000   13.000000   14.000000
max     75.000000   19.000000   19.000000   20.000000
       school  sex         age address famsize Pstatus        Medu  \
count     395  395  395.000000     395     395     395  395.000000
unique      2    2         NaN       2       2       2         NaN
top        GP    F         NaN       U     GT3       T         NaN
freq      349  208         NaN     307     281     354         NaN
mean      NaN  NaN   16.696203     NaN     NaN     NaN    2.749367
std       NaN  NaN    1.276043     NaN     NaN     NaN    1.094735
min       NaN  NaN   15.000000     NaN     NaN     NaN    0.000000
25%       NaN  NaN   16.000000     NaN     NaN     NaN    2.000000
50%       NaN  NaN   17.000000     NaN     NaN     NaN    3.000000
75%       NaN  NaN   18.000000     NaN     NaN     NaN    4.000000
max       NaN  NaN   22.000000     NaN     NaN     NaN    4.000000

              Fedu   Mjob   Fjob  ...      famrel    freetime       goout  \
count   395.000000    395    395  ...  395.000000  395.000000  395.000000
unique         NaN      5      5  ...         NaN         NaN         NaN
top            NaN  other  other  ...         NaN         NaN         NaN
freq           NaN    141    217  ...         NaN         NaN         NaN
mean      2.521519    NaN    NaN  ...    3.944304    3.235443    3.108861
std       1.088201    NaN    NaN  ...    0.896659    0.998862    1.113278
min       0.000000    NaN    NaN  ...    1.000000    1.000000    1.000000
25%       2.000000    NaN    NaN  ...    4.000000    3.000000    2.000000
50%       2.000000    NaN    NaN  ...    4.000000    3.000000    3.000000
75%       3.000000    NaN    NaN  ...    5.000000    4.000000    4.000000
max       4.000000    NaN    NaN  ...    5.000000    5.000000    5.000000

              Dalc        Walc      health    absences          G1  \
count   395.000000  395.000000  395.000000  395.000000  395.000000
unique         NaN         NaN         NaN         NaN         NaN
top            NaN         NaN         NaN         NaN         NaN
freq           NaN         NaN         NaN         NaN         NaN
mean      1.481013    2.291139    3.554430    5.708861   10.908861
std       0.890741    1.287897    1.390303    8.003096    3.319195
min       1.000000    1.000000    1.000000    0.000000    3.000000
25%       1.000000    1.000000    3.000000    0.000000    8.000000
50%       1.000000    2.000000    4.000000    4.000000   11.000000
75%       2.000000    3.000000    5.000000    8.000000   13.000000
max       5.000000    5.000000    5.000000   75.000000   19.000000

                G2          G3
count   395.000000  395.000000
unique         NaN         NaN
top            NaN         NaN
freq           NaN         NaN
mean     10.713924   10.415190
std       3.761505    4.581443
min       0.000000    0.000000
25%       9.000000    8.000000
50%      11.000000   11.000000
75%      13.000000   14.000000
max      19.000000   20.000000

[11 rows x 33 columns]
school        395
sex           395
age           395
address       395
famsize       395
Pstatus       395
Medu          395
Fedu          395
Mjob          395
Fjob          395
reason        395
guardian      395
traveltime    395
studytime     395
failures      395
schoolsup     395
famsup        395
paid          395
activities    395
nursery       395
higher        395
internet      395
romantic      395
famrel        395
freetime      395
goout         395
Dalc          395
Walc          395
health        395
absences      395
G1            395
G2            395
G3            395
dtype: int64
school        0
sex           0
age           0
address       0
famsize       0
Pstatus       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
guardian      0
traveltime    0
studytime     0
failures      0
schoolsup     0
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
famrel        0
freetime      0
goout         0
Dalc          0
Walc          0
health        0
absences      0
G1            0
G2            0
G3            0
dtype: int64
school         2
sex            2
age            8
address        2
famsize        2
Pstatus        2
Medu           5
Fedu           5
Mjob           5
Fjob           5
reason         4
guardian       3
traveltime     4
studytime      4
failures       4
schoolsup      2
famsup         2
paid           2
activities     2
nursery        2
higher         2
internet       2
romantic       2
famrel         5
freetime       5
goout          5
Dalc           5
Walc           5
health         5
absences      34
G1            17
G2            17
G3            18
dtype: int64
school  sex  age  address  famsize  Pstatus  Medu  Fedu  Mjob      Fjob      reason      guardian  traveltime  studytime  failures  schoolsup  famsup  paid  activities  nursery  higher  internet  romantic  famrel  freetime  goout  Dalc  Walc  health  absences  G1  G2  G3
MS      M    21   R        GT3      T        1     1     other     other     course      other     1           1          3         no         no      no    no          no       yes     no        no        5       5         3      3     3     3       3         10  8   7     1
GP      F    15   R        GT3      T        1     1     at_home   other     home        mother    2           4          1         yes        yes     yes   yes         yes      yes     yes       no        3       1         2      1     1     1       2         7   10  10    1
                                                         other     other     reputation  mother    1           2          2         yes        yes     no    no          no       yes     yes       yes       3       3         4      2     4     5       2         8   6   5     1
                                             2     2     at_home   other     reputation  mother    1           1          0         yes        yes     yes   yes         yes      yes     no        no        4       3         1      1     1     2       8         14  13  13    1
                                                   4     services  health    course      mother    1           3          0         yes        yes     yes   yes         yes      yes     yes       no        4       3         2      1     1     5       2         10  9   8     1
                                                                                                                                                                                                                                                                                  ..
                  U        GT3      T        1     2     at_home   services  course      mother    1           2          0         no         no      no    no          no       yes     yes       no        3       2         3      1     2     1       2         16  15  15    1
                                                                   other     course      mother    1           2          0         no         yes     yes   no          no       yes     yes       no        4       3         2      1     1     5       2         10  11  11    1
                                                   1     other     services  course      father    1           2          0         no         yes     yes   no          yes      yes     yes       no        4       4         2      1     2     5       0         8   11  11    1
                                                                   other     home        father    1           2          0         no         yes     no    yes         no       yes     yes       no        4       3         2      2     3     4       2         9   10  10    1
                                                         at_home   other     course      mother    3           1          0         no         yes     no    yes         no       yes     yes       yes       4       3         3      1     2     4       0         8   0   0     1
Name: count, Length: 395, dtype: int64

Module 4-Selecting Data

In [ ]:
import pandas as pd
df=pd.read_csv("//content/Employee.csv")



print(df["Gender"]) # Selecting a Single Column
df[["Education", "City"]] # selecting multiple columns

#Selecting Rows using Index

print(df.iloc[0]) # first row
print(df.iloc[0:5]) # multiple rows
print(df.iloc[-5:]) # last five rows

## Selecting Rows and Columns using loc[]

#loc[] uses row labels (index names) and column names.
# syntax -> df.loc[row_label, column_name]
print(df.loc[0]) # first row
print(df.loc[0:5]) # multiple rows
print(df.loc[-5:]) # last five rows

#Selecting Rows and Columns using iloc[]

#iloc[] uses integer positions.
#syntax -> df.iloc[row_index, column_index]

print(df.iloc[0]) #first row
print(df.iloc[0:5]) #multiple rows
print(df.iloc[-5:]) #last five rows

# Boolean Indexing

#Boolean Indexing returns rows where the condition is True.

# Age greater than 30
df[df["Age"] > 30]

# Age less than 30
df[df["Age"] < 30]
# city is banglore
df[df["City"] == "Bangalore"]

# education is master
df[df["Education"] == "Masters"]

# Filtering Data

df[df["City"] == "Bangalore"] # single condition
df[(df["City"] == "Pune") & # multiple conditions(AND) (
   (df["Age"] > 30)]

df[(df["City"] == "Pune") | # multiple conditions(OR)
   (df["Age"] > 30)]

df[~(df["City"] == "New Delhi")] # NOT condition (changed from Department == Sales)

df[df["City"].isin(["Bangalore", "Pune"])] # using isin()

df[df["Age"].between(25, 35)] # using(between)

df[df["Education"].str.contains("Bachelor", case=False)] # using str.contains()
# using query
df.query("Age > 30")
df.query("City == 'Pune'")
df.query("Age > 30 and ExperienceInCurrentDomain > 3")

df.nlargest(5, "Age") # using nlargest()
df.nsmallest(5, "Age") # using nsmallest()

0         Male
1       Female
2       Female
3         Male
4         Male
         ...
4648    Female
4649      Male
4650      Male
4651      Male
4652      Male
Name: Gender, Length: 4653, dtype: object
Education                    Bachelors
JoiningYear                       2017
City                         Bangalore
PaymentTier                          3
Age                                 34
Gender                            Male
EverBenched                         No
ExperienceInCurrentDomain            0
LeaveOrNot                           0
Name: 0, dtype: object
   Education  JoiningYear       City  PaymentTier  Age  Gender EverBenched  \
0  Bachelors         2017  Bangalore            3   34    Male          No
1  Bachelors         2013       Pune            1   28  Female          No
2  Bachelors         2014  New Delhi            3   38  Female          No
3    Masters         2016  Bangalore            3   27    Male          No
4    Masters         2017       Pune            3   24    Male         Yes

   ExperienceInCurrentDomain  LeaveOrNot
0                          0           0
1                          3           1
2                          2           0
3                          5           1
4                          2           1
      Education  JoiningYear       City  PaymentTier  Age  Gender EverBenched  \
4648  Bachelors         2013  Bangalore            3   26  Female          No
4649    Masters         2013       Pune            2   37    Male          No
4650    Masters         2018  New Delhi            3   27    Male          No
4651  Bachelors         2012  Bangalore            3   30    Male         Yes
4652  Bachelors         2015  Bangalore            3   33    Male         Yes

      ExperienceInCurrentDomain  LeaveOrNot
4648                          4           0
4649                          2           1
4650                          5           1
4651                          2           0
4652                          4           0
Education                    Bachelors
JoiningYear                       2017
City                         Bangalore
PaymentTier                          3
Age                                 34
Gender                            Male
EverBenched                         No
ExperienceInCurrentDomain            0
LeaveOrNot                           0
Name: 0, dtype: object
   Education  JoiningYear       City  PaymentTier  Age  Gender EverBenched  \
0  Bachelors         2017  Bangalore            3   34    Male          No
1  Bachelors         2013       Pune            1   28  Female          No
2  Bachelors         2014  New Delhi            3   38  Female          No
3    Masters         2016  Bangalore            3   27    Male          No
4    Masters         2017       Pune            3   24    Male         Yes
5  Bachelors         2016  Bangalore            3   22    Male          No

   ExperienceInCurrentDomain  LeaveOrNot
0                          0           0
1                          3           1
2                          2           0
3                          5           1
4                          2           1
5                          0           0
      Education  JoiningYear       City  PaymentTier  Age  Gender EverBenched  \
0     Bachelors         2017  Bangalore            3   34    Male          No
1     Bachelors         2013       Pune            1   28  Female          No
2     Bachelors         2014  New Delhi            3   38  Female          No
3       Masters         2016  Bangalore            3   27    Male          No
4       Masters         2017       Pune            3   24    Male         Yes
...         ...          ...        ...          ...  ...     ...         ...
4648  Bachelors         2013  Bangalore            3   26  Female          No
4649    Masters         2013       Pune            2   37    Male          No
4650    Masters         2018  New Delhi            3   27    Male          No
4651  Bachelors         2012  Bangalore            3   30    Male         Yes
4652  Bachelors         2015  Bangalore            3   33    Male         Yes

      ExperienceInCurrentDomain  LeaveOrNot
0                             0           0
1                             3           1
2                             2           0
3                             5           1
4                             2           1
...                         ...         ...
4648                          4           0
4649                          2           1
4650                          5           1
4651                          2           0
4652                          4           0

[4653 rows x 9 columns]
Education                    Bachelors
JoiningYear                       2017
City                         Bangalore
PaymentTier                          3
Age                                 34
Gender                            Male
EverBenched                         No
ExperienceInCurrentDomain            0
LeaveOrNot                           0
Name: 0, dtype: object
   Education  JoiningYear       City  PaymentTier  Age  Gender EverBenched  \
0  Bachelors         2017  Bangalore            3   34    Male          No
1  Bachelors         2013       Pune            1   28  Female          No
2  Bachelors         2014  New Delhi            3   38  Female          No
3    Masters         2016  Bangalore            3   27    Male          No
4    Masters         2017       Pune            3   24    Male         Yes

   ExperienceInCurrentDomain  LeaveOrNot
0                          0           0
1                          3           1
2                          2           0
3                          5           1
4                          2           1
      Education  JoiningYear       City  PaymentTier  Age  Gender EverBenched  \
4648  Bachelors         2013  Bangalore            3   26  Female          No
4649    Masters         2013       Pune            2   37    Male          No
4650    Masters         2018  New Delhi            3   27    Male          No
4651  Bachelors         2012  Bangalore            3   30    Male         Yes
4652  Bachelors         2015  Bangalore            3   33    Male         Yes

      ExperienceInCurrentDomain  LeaveOrNot
4648                          4           0
4649                          2           1
4650                          5           1
4651                          2           0
4652                          4           0

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
5,Bachelors,2016,Bangalore,3,22,Male,No,0,0
19,Bachelors,2016,New Delhi,2,22,Female,No,0,1
25,Bachelors,2013,Bangalore,3,22,Female,Yes,0,0
63,Bachelors,2014,Pune,1,22,Female,No,0,1
91,Bachelors,2015,New Delhi,3,22,Male,No,0,0

Module 5- Missing value in pandas

In [ ]:
import pandas as pd
import numpy as np

data = {
    "Name": ["Aman", "Riya", "Karan", "Priya", np.nan],
    "Age": [22, np.nan, 25, 28, 24],
    "City": ["Delhi", "Mumbai", np.nan, "Lucknow", "Delhi"],
    "Salary": [50000, 60000, np.nan, 75000, 55000]
}

df = pd.DataFrame(data)

print("Original DataFrame")
print(df)
print(df.isnull()) #. used to identify missing value
print(df.isnull().sum()) # count missing value
print(df.notnull()) #. used to identify missing value
# fill with a constant
filled = df.fillna("Unknown")
print(filled)
# fill numeric coulmns
df["Age"] = df["Age"].fillna(df["Age"].mean())

print(df)
# fill multiple columns
df.fillna({
    "Name": "Not Available",
    "City": "Unknown",
    "Salary": 0
}, inplace=True)

print(df)

df.dropna() # removes missing values
# df.replace(old_value, new_value) # used to replace speific values (not limited to missing values)

Original DataFrame
    Name   Age     City   Salary
0   Aman  22.0    Delhi  50000.0
1   Riya   NaN   Mumbai  60000.0
2  Karan  25.0      NaN      NaN
3  Priya  28.0  Lucknow  75000.0
4    NaN  24.0    Delhi  55000.0
    Name    Age   City  Salary
0  False  False  False   False
1  False   True  False   False
2  False  False   True    True
3  False  False  False   False
4   True  False  False   False
Name      1
Age       1
City      1
Salary    1
dtype: int64
    Name    Age   City  Salary
0   True   True   True    True
1   True  False   True    True
2   True   True  False   False
3   True   True   True    True
4  False   True   True    True
      Name      Age     City   Salary
0     Aman     22.0    Delhi  50000.0
1     Riya  Unknown   Mumbai  60000.0
2    Karan     25.0  Unknown  Unknown
3    Priya     28.0  Lucknow  75000.0
4  Unknown     24.0    Delhi  55000.0
    Name    Age     City   Salary
0   Aman  22.00    Delhi  50000.0
1   Riya  24.75   Mumbai  60000.0
2  Karan  25.00      NaN      NaN
3  Priya  28.00  Lucknow  75000.0
4    NaN  24.00    Delhi  55000.0
            Name    Age     City   Salary
0           Aman  22.00    Delhi  50000.0
1           Riya  24.75   Mumbai  60000.0
2          Karan  25.00  Unknown      0.0
3          Priya  28.00  Lucknow  75000.0
4  Not Available  24.00    Delhi  55000.0

            Name    Age     City   Salary
0           Aman  22.00    Delhi  50000.0
1           Riya  24.75   Mumbai  60000.0
2          Karan  25.00  Unknown      0.0
3          Priya  28.00  Lucknow  75000.0
4  Not Available  24.00    Delhi  55000.0

Module 6- Sorting

creating employee data set

In [ ]:
import pandas as pd
data = {
    "Name": ["Aman", "Riya", "Karan", "Priya"],
    "Age": [22, 25, 28, 24],
    "City": ["Delhi", "Mumbai", "Lucknow", "Delhi"],
    "Salary": [50000, 60000, 75000, 55000],
    "department":["HR","IT","Finace","IT"] # Corrected to have 4 elements
}
df = pd.DataFrame(data)
print(df)

    Name  Age     City  Salary department
0   Aman   22    Delhi   50000         HR
1   Riya   25   Mumbai   60000         IT
2  Karan   28  Lucknow   75000     Finace
3  Priya   24    Delhi   55000         IT

Module 7-Data cleaning

topic
duplicated()
drop_duplicates()
rename()
astype()
replace()

1.duplicated()

In [ ]:
import pandas as pd
data = {
    "Name": ["Aman", "Riya", "Karan", "Priya"],
    "Age": [22, 25, 28, 24],
    "City": ["Delhi", "Mumbai", "Lucknow", "Delhi"],

}
df = pd.DataFrame(data)
print(df)

print("/nDuplicate rows:")
print(df.duplicated())

    Name  Age     City
0   Aman   22    Delhi
1   Riya   25   Mumbai
2  Karan   28  Lucknow
3  Priya   24    Delhi
/nDuplicate rows:
0    False
1    False
2    False
3    False
dtype: bool

2.drop_duplicates()

In [ ]:
import pandas as pd
data = {
    "ID":[101,102,103,103,104],
    "Name": ["Aman", "Riya", "Karan", "Priya","Riya"],
    "Age": [22, 25, 28, 24,25],
    "City": ["Delhi", "Mumbai", "Lucknow", "Delhi","Mumbai"],

}
df = pd.DataFrame(data)
print(df)

print("original dataframe")
print(df.drop_duplicates())
print(df)

    ID   Name  Age     City
0  101   Aman   22    Delhi
1  102   Riya   25   Mumbai
2  103  Karan   28  Lucknow
3  103  Priya   24    Delhi
4  104   Riya   25   Mumbai
original dataframe
    ID   Name  Age     City
0  101   Aman   22    Delhi
1  102   Riya   25   Mumbai
2  103  Karan   28  Lucknow
3  103  Priya   24    Delhi
4  104   Riya   25   Mumbai
    ID   Name  Age     City
0  101   Aman   22    Delhi
1  102   Riya   25   Mumbai
2  103  Karan   28  Lucknow
3  103  Priya   24    Delhi
4  104   Riya   25   Mumbai

3.rename

In [ ]:
import pandas as pd
data ={
    "Emp_ID":[101,102,103],
    "Emp_Name":["Aman","Riya","Karan"],
    "Age":[22,25,28],
    "salary":[50000,60000,75000]
}
df=pd.DataFrame(data)
print(df)

print("rename column")

df=pd.DataFrame(data)
print(df)

   Emp_ID Emp_Name  Age  salary
0     101     Aman   22   50000
1     102     Riya   25   60000
2     103    Karan   28   75000
rename column
   Emp_ID Emp_Name  Age  salary
0     101     Aman   22   50000
1     102     Riya   25   60000
2     103    Karan   28   75000

4.astype()

change the data  type of a column

In [ ]:
import pandas as pd

data = {
    "ID" : ["101", "102", "103"],
    "Salary" : ["45000", "60000", "55000"]
}

df = pd.DataFrame(data)

print("Before Conversion:")
print(df.dtypes)

df["ID"] = df["ID"].astype(int)
df["Salary"] = df["Salary"].astype(float)

print("\nAfter Conversion:")
print(df.dtypes)

print(df)

Before Conversion:
ID        object
Salary    object
dtype: object

After Conversion:
ID          int64
Salary    float64
dtype: object
    ID   Salary
0  101  45000.0
1  102  60000.0
2  103  55000.0

5.replace

In [ ]:
import pandas as pd
data={
    "Name":["Aman","Riya","Karan","Priya"],
    "Age":[22,25,28,24],
    "City":["Delhi","Mumbai","Lucknow","Delhi"]
}
df=pd.DataFrame(data)
print("original dataframe")
print(df)

df["Age"]=df["Age"].replace(22,23)
print(df)

print("\nAfter replace")
print(df)

original dataframe
    Name  Age     City
0   Aman   22    Delhi
1   Riya   25   Mumbai
2  Karan   28  Lucknow
3  Priya   24    Delhi
    Name  Age     City
0   Aman   23    Delhi
1   Riya   25   Mumbai
2  Karan   28  Lucknow
3  Priya   24    Delhi

After replace
    Name  Age     City
0   Aman   23    Delhi
1   Riya   25   Mumbai
2  Karan   28  Lucknow
3  Priya   24    Delhi

Module-8 String function

In [ ]:
import pandas as pd

# Sample Dataset
df = pd.DataFrame({
    "Name": ["Amit", "Priya", "Rahul", "Neha", "David"]
})

print(df)

# .str.lower() -> converts all text to lowercase
df["Lower"] = df["Name"].str.lower()

print(df)

# .str.upper() -> Converts all text to uppercase.
df["Upper"] = df["Name"].str.upper()

print(df)

# .str.contains() -> Checks whether a string contains a specific word or character.
df["Contains_a"] = df["Name"].str.contains("a", case=False)

print(df)

# .str.split() -> Splits a string into multiple parts.
df["Split"] = df["Name"].str.split()

print(df)

# .str.replace() -> Replaces a word or character with another.
df["Replaced"] = df["Name"].str.replace("a", "A")

print(df)

# .str.strip() -> Removes leading and trailing spaces.
df["Stripped"] = df["Name"].str.strip()

print(df)

    Name
0   Amit
1  Priya
2  Rahul
3   Neha
4  David
    Name  Lower
0   Amit   amit
1  Priya  priya
2  Rahul  rahul
3   Neha   neha
4  David  david
    Name  Lower  Upper
0   Amit   amit   AMIT
1  Priya  priya  PRIYA
2  Rahul  rahul  RAHUL
3   Neha   neha   NEHA
4  David  david  DAVID
    Name  Lower  Upper  Contains_a
0   Amit   amit   AMIT        True
1  Priya  priya  PRIYA        True
2  Rahul  rahul  RAHUL        True
3   Neha   neha   NEHA        True
4  David  david  DAVID        True
    Name  Lower  Upper  Contains_a    Split
0   Amit   amit   AMIT        True   [Amit]
1  Priya  priya  PRIYA        True  [Priya]
2  Rahul  rahul  RAHUL        True  [Rahul]
3   Neha   neha   NEHA        True   [Neha]
4  David  david  DAVID        True  [David]
    Name  Lower  Upper  Contains_a    Split Replaced
0   Amit   amit   AMIT        True   [Amit]     Amit
1  Priya  priya  PRIYA        True  [Priya]    PriyA
2  Rahul  rahul  RAHUL        True  [Rahul]    RAhul
3   Neha   neha   NEHA        True   [Neha]     NehA
4  David  david  DAVID        True  [David]    DAvid
    Name  Lower  Upper  Contains_a    Split Replaced Stripped
0   Amit   amit   AMIT        True   [Amit]     Amit     Amit
1  Priya  priya  PRIYA        True  [Priya]    PriyA    Priya
2  Rahul  rahul  RAHUL        True  [Rahul]    RAhul    Rahul
3   Neha   neha   NEHA        True   [Neha]     NehA     Neha
4  David  david  DAVID        True  [David]    DAvid    David

Module-9-Group By

topics

1.grouping
2.mean()
3.sum()
4.count()
5.agg()

In [ ]:
import pandas as pd

data = {
    "Employee": ["Aman", "Riya", "Rahul", "Priya", "Karan", "Neha"],
    "Department": ["HR", "IT", "IT", "HR", "Sales", "Sales"],
    "Salary": [40000, 60000, 55000, 45000, 50000, 52000]
}

df = pd.DataFrame(data)

print(df.groupby("Department")) # group by object
print(df.groupby("Department")["Salary"].mean()) # mean of 'Salary' for each group
print(df.groupby("Department")["Salary"].sum()) # sum of 'Salary' for each group
print(df.groupby("Department").count()) # count of each group
print(df.groupby("Department").agg({"Salary": ["mean", "sum"]})) # aggregate

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x7f1b2fe71760>
Department
HR       42500.0
IT       57500.0
Sales    51000.0
Name: Salary, dtype: float64
Department
HR        85000
IT       115000
Sales    102000
Name: Salary, dtype: int64
            Employee  Salary
Department
HR                 2       2
IT                 2       2
Sales              2       2
             Salary
               mean     sum
Department
HR          42500.0   85000
IT          57500.0  115000
Sales       51000.0  102000

Module 10- Merge & Join

1.merge

In [ ]:
import pandas as pd
# Employee Data
employees = pd.DataFrame({
    "Emp_ID": [101, 102, 103, 104],
    "Name": ["Amit", "Neha", "Rahul", "Priya"]
})
# Salary Data
salary = pd.DataFrame({
    "Emp_ID": [101, 102, 103, 104],
    "Salary": [45000, 52000, 48000, 60000]
})
# Merge DataFrames
result = pd.merge(employees, salary, on="Emp_ID")
print(result)

   Emp_ID   Name  Salary
0     101   Amit   45000
1     102   Neha   52000
2     103  Rahul   48000
3     104  Priya   60000

 2. concat()

In [ ]:
import pandas as pd
students1 = pd.DataFrame({
    "Name": ["Amit", "Neha"],
    "Marks": [85, 90]
})
students2 = pd.DataFrame({
    "Name": ["Rahul", "Priya"],
    "Marks": [78, 95]
})
result = pd.concat([students1, students2])
print(result)

    Name  Marks
0   Amit     85
1   Neha     90
0  Rahul     78
1  Priya     95

 Horizontal Concatenation

In [ ]:
import pandas as pd
student = pd.DataFrame({
    "Name": ["Amit", "Neha"]
})
marks = pd.DataFrame({
    "Marks": [85, 90]
})
result = pd.concat([student, marks], axis=1)
print(result)

   Name  Marks
0  Amit     85
1  Neha     90

3. join()

In [ ]:
import pandas as pd
student = pd.DataFrame({
    "Name": ["Amit", "Neha", "Rahul"]
}, index=[1,2,3])
marks = pd.DataFrame({
    "Marks": [85, 90, 78]
}, index=[1,2,3])
result = student.join(marks)
print(result)

    Name  Marks
1   Amit     85
2   Neha     90
3  Rahul     78

Module 11 – Pivot Tables

is used to reshape data by converting unique values from one column into multiple columns. It does not perform aggregation, so
duplicate combinations are not allowed.
keyboard_arrow_down

In [ ]:
import pandas as pd
# Dataset
data = {
    "Employee": ["A", "A", "B", "B"],
    "Month": ["Jan", "Feb", "Jan", "Feb"],
    "Sales": [5000, 7000, 6000, 8000]
}
df = pd.DataFrame(data)
print("Original DataFrame:\n")
print(df)
print("\nPivot Table:\n")
pivot_df = df.pivot(
    index="Employee",
    columns="Month",
    values="Sales"
)
print(pivot_df)

Original DataFrame:

  Employee Month  Sales
0        A   Jan   5000
1        A   Feb   7000
2        B   Jan   6000
3        B   Feb   8000

Pivot Table:

Month      Feb   Jan
Employee
A         7000  5000
B         8000  6000

2. pivot_table()

In [ ]:
import pandas as pd
# Dataset
data = {
    "Department": ["IT", "IT", "HR", "HR", "IT"],
    "Gender": ["Male", "Female", "Male", "Female", "Male"],
    "Salary": [50000, 60000, 45000, 48000, 55000]
}
df = pd.DataFrame(data)
print("Original DataFrame:\n")
print(df)
print("\nPivot Table using Mean:\n")
pivot_table_df = df.pivot_table(
    values="Salary",
    index="Department",
    columns="Gender",
    aggfunc="mean"
)
print(pivot_table_df)

Original DataFrame:

  Department  Gender  Salary
0         IT    Male   50000
1         IT  Female   60000
2         HR    Male   45000
3         HR  Female   48000
4         IT    Male   55000

Pivot Table using Mean:

Gender       Female     Male
Department
HR          48000.0  45000.0
IT          60000.0  52500.0

3. crosstab()

In [ ]:
import pandas as pd
# Dataset
data = {
    "Department": ["IT", "IT", "HR", "HR", "IT", "Sales", "Sales"],
    "Gender": ["Male", "Female", "Male", "Female", "Male", "Female", "Male"]
}
df = pd.DataFrame(data)
print("Original DataFrame:\n")
print(df)
print("\nCrossTab:\n")
cross = pd.crosstab(
    df["Department"],
    df["Gender"]
)
print(cross)

Original DataFrame:

  Department  Gender
0         IT    Male
1         IT  Female
2         HR    Male
3         HR  Female
4         IT    Male
5      Sales  Female
6      Sales    Male

CrossTab:

Gender      Female  Male
Department
HR               1     1
IT               1     2
Sales            1     1

Module 12 – Date & Time

Topics
to_datetime()
datetime column
day
month
year
weekday

1. to_datetime()

In [ ]:
import pandas as pd
data = {
    "Employee": ["Amit", "Priya", "Rahul"],
    "Joining_Date": ["2023-01-15", "2022-06-20", "2021-11-10"]
}
df = pd.DataFrame(data)
df["Joining_Date"] = pd.to_datetime(df["Joining_Date"])
print(df)
print(df.dtypes)

  Employee Joining_Date
0     Amit   2023-01-15
1    Priya   2022-06-20
2    Rahul   2021-11-10
Employee                object
Joining_Date    datetime64[ns]
dtype: object